[achat]
montant = 200
zone = ['Abis', 'A', 'B1', 'B2', 'C']
surface = 50
surface_annexes = 0

[credit]
montant = 200
duree = 20
taux_interet = 1.10
taux_assurance = 0.020

[fiscalite]
regime = ['Micro-Foncier', 'Foncier Réel', 'Micro-BIC', 'BIC Réel (LMNP)']
tmi = [30, 11, 41, 45]
prelevements_sociaux = 17.2

[revenus]
loyer_hc = 1400
loyer_charges = 150
vacance_locative_mois_par_an = 0.50

[charges]
taux_notaire = 0.075
agence = 1.00
dossier_bancaire = 0.50
garantie_financement = 0.50
courtier = 1.00
travaux = 1.00
achat_mobilier = 1.50
assurance_pno = 0.20
assurance_loyer_impaye = 0.20
taxe_fonciere = 1.00
copropriete = 0.50
taxe_cfe = 0.75
comptable_cga = 0.75

[cosse] # https://www.pap.fr/actualites/louer-abordable-et-payer-moins-d-impot-avec-le-cosse-ancien-a19203
types = ['intermediaire', 'social']
[cosse.deduction]
[cosse.deduction.intermediaire]
Abis = 0.3
A = 0.3
B1 = 0.3
B2 = 0.15
C = 0  # Impossible
[cosse.deduction.social]
Abis = 0.7
A = 0.7
B1 = 0.7
B2 = 0.5
C = 0.5  # Si travaux
[cosse.plafond]
[cosse.plafond.intermediaire]
Abis = 17.55
A = 13.04
B1 = 10.51
B2 = 9.13
C = 9.13
[cosse.plafond.social]
Abis = 12.27
A = 9.44
B1 = 8.13
B2 = 7.81
C = 7.25


